---
dist: xenial
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian8
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: centos7

# Cache Ansible and Molecule to speed things up
cache:
  - pip

before_install:
  # Upgrade Docker to work with docker-py.
  - curl https://gist.githubusercontent.com/geerlingguy/ce883ad4aec6a5f1187ef93bd338511e/raw/36612d28981d92863f839c5aefe5b7dd7193d6c6/travis-ci-docker-upgrade.sh | sudo bash

install:
  # Install Ansible, Molecule and docker-py
  - pip install ansible molecule docker ansible-lint flake8

  # Log Docker, Ansible and Molecule version
  - docker --version
  - ansible --version
  - molecule --version

before_script:
  - cd .. && mv ansible-role-docker jgeusebroek.docker && cd jgeusebroek.docker

script:
  # Start test
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
